baseurl = "https://el-aurens.github.io/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "El Aurens"
canonifyurls  = true

DefaultContentLanguage = "fr"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
googleAnalytics = "UA-119584387-1"
Paginate=5

[permalinks]
  post = "/:sections/:year/:month/:title/"

[Params]
  subtitle = "El Aurens Personal Website"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "El Aurens"
  email = "te.elaurens@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "el-aurens"
  github = "el-aurens"
  twitter = "el-aurens"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"


[[menu.main]]
    name = "Blog"
    url = "post/blog"
    weight = 1
[[menu.main]]
    name = "Hacker News"
    url = "post/hackernews"
    weight = 2
[[menu.main]]
    name = "Tutoriaux"
    url = "post/blog/tutorials"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4
[[menu.main]]
    name = "A Propos"
    url = "page/about/"
    weight = 5

# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2
#
# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1
#
# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2
#
# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3


[taxonomies]
tag = "tags"


[languages]
  [languages.fr]
    title = "El Aurens"
    weight = 1
  [languages.fr.Params]
    subtitle = "Site Personnel d'El Aurens"
  [languages.en]
    title = "El Aurens's Blog"
    weight = 2
  [[languages.en.menu.main]]
    name = "Blog"
    url = "post/blog"
    weight = 1
  [[languages.en.menu.main]]
    name = "Hacker News"
    url = "post/hackernews"
    weight = 2
  [[languages.en.menu.main]]
    name = "Tutorials"
    url = "post/blog/tutorials"
    weight = 3
  [[languages.en.menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4
  [[languages.en.menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5
